[package]
name = "z2p"
version = "0.1.0"
authors = ["Takehiro KAMADA <takehiro.kamada@mo-t.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
